# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: Ibex Private CI

on:
  push:
    tags:
      - "*"
  merge_group:
    types:
      - checks_requested
  pull_request_target:
    branches:
      - "*"

permissions:
  statuses: write

jobs:
  trigger:
    name: Trigger Private CI
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Private CI
        run: |
          PAYLOAD='{"event_type":"cross-repo-ci","client_payload":{"target":"${{ github.repository_owner }}/lowrisc-private-ci/master/test.yml","sha":"${{ github.event.pull_request.head.sha || github.sha }}"'
          if [ -n "${{ github.event.pull_request.number }}" ]; then
            PAYLOAD+=',"pull_request":${{ github.event.pull_request.number }}"'
          fi
          PAYLOAD+='}}'
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}>" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d "$PAYLOAD"
